version: '3'

services:
    app:
        image: fed
        build:
            dockerfile: Dockerfile
        environment:
            - PORT=${PORT}
        ports:
            - ${PORT}:${PORT}
        volumes:
            - ./app:/app